import type { Metadata } from 'next';

import { primaryFont, secondaryFont } from '@/configs/fonts';
import { IChildren } from '@/types/children.types';

import { Providers } from './providers';

import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Vocab Builder',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

const RootLayout: React.FC<IChildren> = ({ children }) => {
    return (
        <html lang="en">
            <body className={`${primaryFont.variable} ${secondaryFont.variable} antialiased`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
};

export default RootLayout;
